"""add notes column to profiles

Revision ID: 0af99dc2a384
Revises: fdff3ae8fd85
Create Date: 2026-08-03 23:42:37.177230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0af99dc2a384'
down_revision: Union[str, Sequence[str], None] = 'fdff3ae8fd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'notes')
    # ### end Alembic commands ###
