"""add address column to profiles

Revision ID: a74ccf47ab58
Revises: fdff3ae8fd85
Create Date: 2026-08-11 03:26:21.725820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a74ccf47ab58'
down_revision: Union[str, Sequence[str], None] = 'fdff3ae8fd85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('address', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'address')
    # ### end Alembic commands ###
